# Generated by Django 4.2.30 on 2026-08-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafariPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('half-day', 'Half-Day Game Drive'), ('full-day', 'Full-Day Expedition'), ('luxury-camp', 'Luxury Tented Camp Package'), ('photography', 'Photography Special')], default='half-day', max_length=50)),
                ('category_label', models.CharField(default='HALF-DAY GAME DRIVE', max_length=100)),
                ('tag_class', models.CharField(default='tag-sage', max_length=50)),
                ('price', models.CharField(default='$120', max_length=50)),
                ('price_unit', models.CharField(default='per 4x4 jeep (up to 6 guests)', max_length=100)),
                ('duration', models.CharField(default='5 Hours (05:30 AM – 10:30 AM)', max_length=100)),
                ('vehicle', models.CharField(default='Private Modified Toyota Land Cruiser 4x4', max_length=200)),
                ('inclusions', models.TextField(help_text='Separate inclusions with newlines')),
                ('highlights', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
