# Generated by Django 4.2.30 on 2026-08-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='breakfast_addon_price',
            field=models.CharField(blank=True, default='+$15 USD / Person (Optional Add-on)', max_length=100),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the safari package experience'),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='exclusions',
            field=models.TextField(blank=True, help_text='Items NOT included (Separate with newlines e.g. Park Tickets, Tips)'),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='includes_breakfast',
            field=models.BooleanField(default=False, help_text='Check if breakfast is included in base price'),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='includes_tickets',
            field=models.BooleanField(default=False, help_text='Check if Yala entrance tickets are included in base price'),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='price_type',
            field=models.CharField(choices=[('jeep_only', 'Jeep-Only Private Drive (Add-ons Optional)'), ('per_person', 'Per-Person All-Inclusive (Shared / Glamping)')], default='jeep_only', max_length=30),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='ticket_addon_price',
            field=models.CharField(blank=True, default='$40 USD / Adult Ticket (Optional at Gate)', max_length=100),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='highlights',
            field=models.TextField(help_text='Key safari attraction points'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='inclusions',
            field=models.TextField(help_text='Items included (Separate with newlines)'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='price',
            field=models.CharField(default='$120', help_text='Primary price string shown on card (e.g. $120)', max_length=50),
        ),
    ]
