# Generated by Django 3.1.12 on 2026-08-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_safaripackage_breakfast_addon_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='imageUrl',
            field=models.CharField(blank=True, help_text='Cloudinary or image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='mealPrice',
            field=models.CharField(blank=True, default='0', help_text='Meal price e.g. 10 or 0', max_length=50),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='slug',
            field=models.CharField(blank=True, help_text='URL friendly slug identifier e.g. bundala-tour-7-hours', max_length=200),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='ticketPrice',
            field=models.CharField(blank=True, default='0', help_text='Ticket price e.g. 30 or 0', max_length=50),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='category',
            field=models.CharField(choices=[('half-day', 'Half-Day Game Drive'), ('full-day', 'Full-Day Expedition'), ('luxury-camp', 'Luxury Tented Camp Package'), ('photography', 'Photography Special'), ('shared-safari', 'Shared Safari Tour')], default='half-day', max_length=50),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='highlights',
            field=models.TextField(help_text='Key safari attraction points (Separate with newlines)'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='price',
            field=models.CharField(default='$120', help_text='Primary price string shown on card (e.g. $62.99 or $49)', max_length=50),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
