# Generated by Django 3.1.12 on 2026-08-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260818_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafariBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_code', models.CharField(default='+94', max_length=10)),
                ('phone_number', models.CharField(max_length=50)),
                ('safari_date', models.DateField()),
                ('guests', models.IntegerField(default=2)),
                ('include_meals', models.BooleanField(default=False)),
                ('meals_price_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('include_tickets', models.BooleanField(default=False)),
                ('tickets_price_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
