# Generated by Django 3.1.12 on 2026-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_safaribooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaribooking',
            name='adult_guests',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='safaribooking',
            name='child_guests',
            field=models.IntegerField(default=0, help_text='Age 6-16 ($20 USD)'),
        ),
        migrations.AddField(
            model_name='safaribooking',
            name='meal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='safaribooking',
            name='under6_guests',
            field=models.IntegerField(default=0, help_text='Under 6 (FREE)'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='breakfast_addon_price',
            field=models.CharField(blank=True, default='+$10 USD / Person (Optional Add-on)', max_length=100),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='ticket_addon_price',
            field=models.CharField(blank=True, default='$46 Adult (16+) | $20 Child (6-16) | Under 6 Free', max_length=100),
        ),
    ]
