# Generated by Django 3.1.12 on 2026-08-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20260818_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='childTicketPrice',
            field=models.CharField(blank=True, default='20', help_text='Child ticket price (age 6-16) e.g. 20 or 10', max_length=50),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='ticketPrice',
            field=models.CharField(blank=True, default='0', help_text='Adult ticket price e.g. 46 or 30', max_length=50),
        ),
    ]
