# Generated by Django 3.1.12 on 2026-08-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20260818_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload image file from local device (auto-uploads to Cloudinary if configured) OR paste direct URL in Image URL field below', null=True, upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='imageUrl',
            field=models.CharField(blank=True, help_text='Cloudinary or image URL (Auto-filled when uploading local image file)', max_length=500),
        ),
    ]
