# Generated by Django 3.1.12 on 2026-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20260818_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='image_urls',
            field=models.TextField(blank=True, help_text='Additional image URLs / Cloudinary URLs for gallery (Separate multiple URLs with newlines)'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='imageUrl',
            field=models.CharField(blank=True, help_text='Primary Cloudinary or image URL (Auto-filled when uploading local image file)', max_length=500),
        ),
    ]
