# Generated by Django 3.1.12 on 2026-08-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20260818_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, help_text='URL slug identifier e.g. Yala-National-Park-The-Wildlife-Paradise-of-Sri-Lanka', max_length=250)),
                ('category', models.CharField(default='WILDLIFE LOG', max_length=100)),
                ('author', models.CharField(default='Yala Leopard Tracks Naturalist', max_length=100)),
                ('image_file', models.ImageField(blank=True, help_text='Upload image file from local device (auto-uploads to Cloudinary) OR paste Cloudinary URL below', null=True, upload_to='blogs/')),
                ('imageUrl', models.CharField(blank=True, help_text='Cloudinary or image URL', max_length=500)),
                ('content', models.TextField(help_text='Full blog post story & article content')),
                ('featured', models.BooleanField(default=False, help_text='Check if this blog post should be highlighted as Featured Hero story')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
