# Generated by Django 3.1.12 on 2026-08-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('leopard', 'Leopard Sightings'), ('drives', 'Game Drives'), ('camp', 'Luxury Camp Stays'), ('photo', 'Wildlife Photography')], default='leopard', max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('origin', models.CharField(default='London, UK', max_length=150)),
                ('date', models.CharField(default='August 2026', max_length=50)),
                ('package', models.CharField(default='Yala Block 1 Morning Leopard Game Drive', max_length=200)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guest Review',
                'verbose_name_plural': 'Guest Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='WILD YALA SAFARIS', help_text='Main Hero Title e.g. WILD YALA SAFARIS', max_length=200)),
                ('subtitle', models.CharField(default="Ceylon's premier 4x4 game drives & luxury glamping.", help_text='Hero Subtitle / Description', max_length=300)),
                ('badge_text', models.CharField(blank=True, default='🌿 YALA LEOPARD TRACKS', help_text='Pill Badge Tag text e.g. 🌿 YALA LEOPARD TRACKS', max_length=100)),
                ('image_file', models.ImageField(blank=True, help_text='Upload hero image file from local device (auto-uploads to Cloudinary if configured) OR paste direct URL below', null=True, upload_to='hero/')),
                ('imageUrl', models.CharField(blank=True, default='https://res.cloudinary.com/dkfnpmzpv/image/upload/v1786355872/blogs/amvi8vrath9rtjzrk01m.jpg', help_text='Hero background image Cloudinary or static URL', max_length=500)),
                ('button_primary_text', models.CharField(default='EXPLORE PACKAGES', max_length=100)),
                ('button_primary_url', models.CharField(default='/packages/', max_length=200)),
                ('button_secondary_text', models.CharField(default='BOOK SAFARI', max_length=100)),
                ('button_secondary_url', models.CharField(default='/contact/', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Check if this Hero Section configuration is active on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, help_text='URL friendly slug identifier e.g. 5-day-sri-lanka-escape', max_length=250)),
                ('route', models.CharField(blank=True, help_text='Tour route overview e.g. Colombo → Sigiriya → Kandy → Ella → Colombo', max_length=500)),
                ('price', models.CharField(default='280', help_text='Tour price string e.g. 280 or $280', max_length=50)),
                ('duration', models.CharField(default='5 Days / 4 Nights', help_text='Tour duration e.g. 5 Days / 4 Nights', max_length=100)),
                ('image_file', models.ImageField(blank=True, help_text='Upload tour image file from local device', null=True, upload_to='tours/')),
                ('imageUrl', models.CharField(blank=True, help_text='Cloudinary or direct image URL', max_length=500)),
                ('isFeatured', models.BooleanField(default=False, help_text='Check if this tour should be highlighted on the tours page')),
                ('description', models.TextField(help_text='Short description overview')),
                ('longDescription', models.TextField(blank=True, help_text='Detailed journey overview story')),
                ('highlights', models.TextField(help_text='Key highlights (Separate multiple points with newlines)')),
                ('inclusions', models.TextField(help_text='Service inclusions (Separate multiple points with newlines)')),
                ('exclusions', models.TextField(help_text='Service exclusions (Separate multiple points with newlines)')),
                ('seoKeywords', models.TextField(blank=True, help_text='SEO keywords separated by commas')),
                ('itinerary_json', models.TextField(blank=True, help_text='JSON string array of day-by-day itinerary items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tour Package',
                'verbose_name_plural': 'Tour Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
