# Generated by Django 3.1.12 on 2026-08-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_guestreview_herosection_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestreview',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='guestreview',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='guestreview',
            name='source',
            field=models.CharField(default='Google Maps', max_length=50),
        ),
    ]
