# Generated by Django 3.1.12 on 2026-08-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20260820_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('ticket_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('foreign_adults', models.IntegerField(default=1)),
                ('foreign_children', models.IntegerField(default=0)),
                ('saarc_adults', models.IntegerField(default=0)),
                ('saarc_children', models.IntegerField(default=0)),
                ('local_adults', models.IntegerField(default=0)),
                ('local_children', models.IntegerField(default=0)),
                ('infants', models.IntegerField(default=0)),
                ('jeeps', models.IntegerField(default=1)),
                ('cars', models.IntegerField(default=0)),
                ('buses', models.IntegerField(default=0)),
                ('entry_fees_lkr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vehicle_fees_lkr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('service_fee_lkr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('subtotal_lkr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_lkr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gateway_fee_lkr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_lkr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DWC Permit Request',
                'verbose_name_plural': 'DWC Permit Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
