# Generated by Django 3.1.12 on 2026-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_permitrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermitRequest',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Discoveryala Naturalist', max_length=100),
        ),
    ]
