# Generated by Django 3.1.12 on 2026-08-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20260822_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Full blog post story & article content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='imageUrl',
            field=models.CharField(blank=True, default='', help_text='Cloudinary or image URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(blank=True, default='', help_text='URL slug identifier e.g. Yala-National-Park-The-Wildlife-Paradise-of-Sri-Lanka', max_length=250),
        ),
        migrations.AlterField(
            model_name='guestreview',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='safaribooking',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='safaribooking',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='safaribooking',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the safari package experience'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='exclusions',
            field=models.TextField(blank=True, default='', help_text='Items NOT included (Separate with newlines e.g. Park Tickets, Tips)'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='highlights',
            field=models.TextField(blank=True, default='', help_text='Key safari attraction points (Separate with newlines)'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='imageUrl',
            field=models.CharField(blank=True, default='', help_text='Primary Cloudinary or image URL (Auto-filled when uploading local image file)', max_length=500),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='image_urls',
            field=models.TextField(blank=True, default='', help_text='Additional image URLs / Cloudinary URLs for gallery (Separate multiple URLs with newlines)'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='inclusions',
            field=models.TextField(blank=True, default='', help_text='Items included (Separate with newlines)'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='slug',
            field=models.CharField(blank=True, default='', help_text='URL friendly slug identifier e.g. bundala-tour-7-hours', max_length=200),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short description overview'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='exclusions',
            field=models.TextField(blank=True, default='', help_text='Service exclusions (Separate multiple points with newlines)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='highlights',
            field=models.TextField(blank=True, default='', help_text='Key highlights (Separate multiple points with newlines)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='imageUrl',
            field=models.CharField(blank=True, default='', help_text='Cloudinary or direct image URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='tour',
            name='inclusions',
            field=models.TextField(blank=True, default='', help_text='Service inclusions (Separate multiple points with newlines)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary_json',
            field=models.TextField(blank=True, default='', help_text='JSON string array of day-by-day itinerary items'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='longDescription',
            field=models.TextField(blank=True, default='', help_text='Detailed journey overview story'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='route',
            field=models.CharField(blank=True, default='', help_text='Tour route overview e.g. Colombo → Sigiriya → Kandy → Ella → Colombo', max_length=500),
        ),
        migrations.AlterField(
            model_name='tour',
            name='seoKeywords',
            field=models.TextField(blank=True, default='', help_text='SEO keywords separated by commas'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.CharField(blank=True, default='', help_text='URL friendly slug identifier e.g. 5-day-sri-lanka-escape', max_length=250),
        ),
    ]
