# Generated by Django 4.2.30 on 2026-09-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_blogpost_id_alter_guestreview_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safaripackage',
            name='vehicle',
            field=models.CharField(default='Private 4x4 Safari Jeep', max_length=200),
        ),
    ]
